; Auto-generated by tools/script_compiler.py
.setcpu "6502"
.export script_start
.segment "RODATA"
script_start:
LEVEL_1:
    .byte $01, $32, $64
    .byte $02
    .word LEVEL_1
    .byte $04, $3C
    .byte $05, $00
    .byte $03, $00
    .byte $00
