#!/usr/bin/env python3
"""Compile high-level NES game script into ca65 bytecode assembly."""
from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple

OP_END = 0x00
OP_PLAYER_SPAWN = 0x01
OP_IF_START_GOTO = 0x02
OP_SOUND_PLAY = 0x03
OP_WAIT_FRAMES = 0x04
OP_PLAY_MUSIC = 0x05
OP_LOAD_LEVEL = 0x06


@dataclass
class EmitItem:
    kind: str  # 'label'|'bytes'|'fixup'
    value: object


def strip_comment(line: str) -> str:
    return line.split("//", 1)[0].strip()


def parse_script(lines: List[str]) -> Tuple[List[EmitItem], Dict[str, int], Dict[str, int], Dict[str, int]]:
    items: List[EmitItem] = []
    labels: Dict[str, int] = {}
    music_ids: Dict[str, int] = {}
    sound_ids: Dict[str, int] = {}
    level_ids: Dict[str, int] = {"LEVEL_1": 0}
    pc = 0

    for raw in lines:
        line = strip_comment(raw)
        if not line:
            continue

        if line.startswith("DEFINE_OBJECT") or line == "END_OBJECT":
            continue
        if any(line.startswith(prefix) for prefix in ("SPRITESET", "HITBOX", "GRAVITY", "SPEED", "ANIMATION", "PLACE_ENEMY", "ON_COLLISION", "LOAD_BACKGROUND")):
            continue

        m_label = re.match(r'^([A-Za-z_][A-Za-z0-9_]*)\s*:\s*$', line)
        if m_label:
            name = m_label.group(1)
            labels[name] = pc
            items.append(EmitItem("label", name))
            continue

        m_spawn = re.match(r'^PLACE_OBJECT\s+PLAYER\s*,\s*start_x\s*=\s*(\d+)\s*,\s*start_y\s*=\s*(\d+)\s*$', line)
        if m_spawn:
            x, y = int(m_spawn.group(1)), int(m_spawn.group(2))
            items.append(EmitItem("bytes", [OP_PLAYER_SPAWN, x & 0xFF, y & 0xFF]))
            pc += 3
            continue

        m_if = re.match(r'^IF\s*\(\s*PRESSED_START\s*\)\s*GOTO\s*"([A-Za-z_][A-Za-z0-9_]*)"\s*$', line)
        if m_if:
            target = m_if.group(1)
            items.append(EmitItem("bytes", [OP_IF_START_GOTO]))
            items.append(EmitItem("fixup", target))
            pc += 3
            continue

        m_wait = re.match(r'^WAIT_FRAMES\((\d+)\)\s*$', line)
        if m_wait:
            frames = int(m_wait.group(1))
            items.append(EmitItem("bytes", [OP_WAIT_FRAMES, frames & 0xFF]))
            pc += 2
            continue

        m_music = re.match(r'^PLAY_MUSIC\s*"([A-Za-z0-9_]+)"\s*$', line)
        if m_music:
            name = m_music.group(1)
            if name not in music_ids:
                music_ids[name] = len(music_ids)
            items.append(EmitItem("bytes", [OP_PLAY_MUSIC, music_ids[name]]))
            pc += 2
            continue

        m_sound = re.match(r'^SOUND_PLAY\s*"([A-Za-z0-9_]+)"\s*$', line)
        if m_sound:
            name = m_sound.group(1)
            if name not in sound_ids:
                sound_ids[name] = len(sound_ids)
            items.append(EmitItem("bytes", [OP_SOUND_PLAY, sound_ids[name]]))
            pc += 2
            continue

        raise ValueError(f"Unsupported script line: {line}")

    items.append(EmitItem("bytes", [OP_END]))
    return items, labels, music_ids, sound_ids


def emit_asm(items: List[EmitItem], labels: Dict[str, int]) -> str:
    out: List[str] = []
    out.append("; Auto-generated by tools/script_compiler.py")
    out.append('.setcpu "6502"')
    out.append('.export script_start')
    out.append('.segment "RODATA"')
    out.append('script_start:')

    for item in items:
        if item.kind == "label":
            out.append(f"{item.value}:")
        elif item.kind == "bytes":
            b = item.value
            out.append("    .byte " + ", ".join(f"${x:02X}" for x in b))
        elif item.kind == "fixup":
            label = str(item.value)
            if label not in labels:
                raise ValueError(f"Unknown GOTO label: {label}")
            out.append(f"    .word {label}")
        else:
            raise ValueError(f"Unknown item kind: {item.kind}")

    return "\n".join(out) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Compile .script to ca65 asm")
    parser.add_argument("input", type=Path)
    parser.add_argument("-o", "--output", type=Path, required=True)
    args = parser.parse_args()

    source = args.input.read_text(encoding="utf-8").splitlines()
    items, labels, _, _ = parse_script(source)
    asm_text = emit_asm(items, labels)
    args.output.write_text(asm_text, encoding="utf-8")


if __name__ == "__main__":
    main()
